language: node_js

node_js:
  - "node"

sudo: false

script:
  - cp config.sample.js config.js
  - npm test

notifications:
  email: false

after_success:
  - rm gcrb_bot.sqlite
  - npm run coveralls
